---
name: Build Image on PR
'on':
  pull_request:
    branches:
      - develop
      - master
      - main
    types:
    - opened
    - synchronize
    - ready_for_review
    - closed
jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out GitHub Repo
      if: github.event.pull_request.draft == false
      with:
        ref: "${{ github.event.pull_request.head.sha }}"
      uses: actions/checkout@v2
    - name: Build And Push To Packages
      if: github.event.pull_request.draft == false && github.event.action != 'closed' && github.event.pull_request.merged != true
      env:
        PR: "${{ github.event.pull_request.number }}"
        SHA: "${{ github.event.pull_request.head.sha }}"
        DOCKER_ACTOR: "${{ secrets.GHCR_USERNAME }}"
        DOCKER_TOKEN: "${{ secrets.GHCR_TOKEN }}"
      run: "./.github/workflows/scripts/pr_build_tag.sh\n"
    - name: Tag Latest Image On Merge
      if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
      env:
        PR: "${{ github.event.pull_request.number }}"
        SHA: "${{ github.event.pull_request.head.sha }}"
        DOCKER_ACTOR: "${{ secrets.GHCR_USERNAME }}"
        DOCKER_TOKEN: "${{ secrets.GHCR_TOKEN }}"
      run: "./.github/workflows/scripts/tag_on_pr_merge.sh\n"
